// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mfjassociates.utilities.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.mfjassociates.utilities.domain.Prefix;
import net.mfjassociates.utilities.domain.PrefixDataOnDemand;
import net.mfjassociates.utilities.domain.PrefixIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrefixIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrefixIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrefixIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PrefixIntegrationTest: @Transactional;
    
    @Autowired
    PrefixDataOnDemand PrefixIntegrationTest.dod;
    
    @Test
    public void PrefixIntegrationTest.testCountPrefixes() {
        Assert.assertNotNull("Data on demand for 'Prefix' failed to initialize correctly", dod.getRandomPrefix());
        long count = Prefix.countPrefixes();
        Assert.assertTrue("Counter for 'Prefix' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrefixIntegrationTest.testFindPrefix() {
        Prefix obj = dod.getRandomPrefix();
        Assert.assertNotNull("Data on demand for 'Prefix' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prefix' failed to provide an identifier", id);
        obj = Prefix.findPrefix(id);
        Assert.assertNotNull("Find method for 'Prefix' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Prefix' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PrefixIntegrationTest.testFindPrefixEntries() {
        Assert.assertNotNull("Data on demand for 'Prefix' failed to initialize correctly", dod.getRandomPrefix());
        long count = Prefix.countPrefixes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Prefix> result = Prefix.findPrefixEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Prefix' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Prefix' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrefixIntegrationTest.testFlush() {
        Prefix obj = dod.getRandomPrefix();
        Assert.assertNotNull("Data on demand for 'Prefix' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prefix' failed to provide an identifier", id);
        obj = Prefix.findPrefix(id);
        Assert.assertNotNull("Find method for 'Prefix' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrefix(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Prefix' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrefixIntegrationTest.testMergeUpdate() {
        Prefix obj = dod.getRandomPrefix();
        Assert.assertNotNull("Data on demand for 'Prefix' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prefix' failed to provide an identifier", id);
        obj = Prefix.findPrefix(id);
        boolean modified =  dod.modifyPrefix(obj);
        Integer currentVersion = obj.getVersion();
        Prefix merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Prefix' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrefixIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Prefix' failed to initialize correctly", dod.getRandomPrefix());
        Prefix obj = dod.getNewTransientPrefix(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Prefix' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Prefix' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Prefix' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PrefixIntegrationTest.testRemove() {
        Prefix obj = dod.getRandomPrefix();
        Assert.assertNotNull("Data on demand for 'Prefix' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Prefix' failed to provide an identifier", id);
        obj = Prefix.findPrefix(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Prefix' with identifier '" + id + "'", Prefix.findPrefix(id));
    }
    
}
