// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mfjassociates.utilities.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.mfjassociates.utilities.domain.Prefix;
import net.mfjassociates.utilities.domain.PrefixDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect PrefixDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PrefixDataOnDemand: @Component;
    
    private Random PrefixDataOnDemand.rnd = new SecureRandom();
    
    private List<Prefix> PrefixDataOnDemand.data;
    
    public Prefix PrefixDataOnDemand.getNewTransientPrefix(int index) {
        Prefix obj = new Prefix();
        setCode(obj, index);
        setCreated(obj, index);
        setInUse(obj, index);
        setUpdated(obj, index);
        return obj;
    }
    
    public void PrefixDataOnDemand.setCode(Prefix obj, int index) {
        String code = "c" + index;
        if (code.length() > 2) {
            code = code.substring(0, 2);
        }
        obj.setCode(code);
    }
    
    public void PrefixDataOnDemand.setCreated(Prefix obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void PrefixDataOnDemand.setInUse(Prefix obj, int index) {
        Boolean inUse = false;
        obj.setInUse(inUse);
    }
    
    public void PrefixDataOnDemand.setUpdated(Prefix obj, int index) {
        Date updated = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdated(updated);
    }
    
    public Prefix PrefixDataOnDemand.getSpecificPrefix(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Prefix obj = data.get(index);
        Long id = obj.getId();
        return Prefix.findPrefix(id);
    }
    
    public Prefix PrefixDataOnDemand.getRandomPrefix() {
        init();
        Prefix obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Prefix.findPrefix(id);
    }
    
    public boolean PrefixDataOnDemand.modifyPrefix(Prefix obj) {
        return false;
    }
    
    public void PrefixDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Prefix.findPrefixEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Prefix' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Prefix>();
        for (int i = 0; i < 10; i++) {
            Prefix obj = getNewTransientPrefix(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
