// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mfjassociates.utilities.domain;

import javax.persistence.Entity;
import net.mfjassociates.utilities.domain.Client;

privileged aspect Client_Roo_Jpa_Entity {
    
    declare @type: Client: @Entity;
    
}
